# Author: Pankil Shah
# Created on: 03/13/2021
# Description: Parse a corpus, create indexing and dump the sentences into the database 

import logic
import datetime
import sys
from os import listdir
from os.path import isfile, join
from collections import defaultdict
import json
import csv

def PreProcess(row):
    untagged_row = row[0]
    untagged_row_words = untagged_row.split()
    untagged_row_words = untagged_row_words[1:]
    untagged_row = " ".join(untagged_row_words) 
    tagged_row = row[1]
    return tagged_row, untagged_row

def ParseCorpus(language, path):
    tagged_sentences = []
    untagged_sentences = []
    dictionary = defaultdict(list)
    document_id = 1
    file_name = path.split("\\")[-1]
    values = ""
    language_id = str(logic.GetLanguageId(language))
    
    if language_id == "-1":
        sys.exit("Language not found in the database.")

    with open(path, 'r', encoding="utf-8") as file:
        reader = csv.reader(file)
        for row in reader:
            tagged_row, untagged_row = PreProcess(row)
            tagged_sentences.append(tagged_row)
            untagged_sentences.append(untagged_row)

    # Index the words in tagged sentences
    for line_id, sentence in enumerate(tagged_sentences, start=1):
        dictionary = logic.CreateIndexing(language, sentence, line_id, dictionary)   
    logic.StoreIndexing(language, json.dumps(dictionary))

    # Insert untagged sentences into the database
    corpus_table = language.lower() + "_corpus" 
    if(not logic.isCorpusLoaded(corpus_table)):  
        for sentence in untagged_sentences:
            sentence = sentence.replace("'","")
            values += "(" + language_id + ", " + str(document_id) + ", " + "'" + file_name + "', " + "'" + sentence + "', " + "'" + str(datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')) + "'),"
        values = values[:-1]
        query = "insert into " + corpus_table + " (Lang_ID, Doc_ID, Doc_Name, Line_Text, Last_Update) values " + values
        logic.SQLInsertQuery(query)

def Main():
    # Example path: 'E:\\SLU\\Sem1\\Principles of SD\\Project Material\\englishtaggedcorpus.csv'
    path = input("Enter path of the tagged corpus file(.csv) generated by tagger: ")
    language = input("Enter language: ")
    ParseCorpus(language, path)

Main()